name: image_viewer
description: A Flutter project for viewing and processing images.

# Các thông tin khác...
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  image: ^3.0.1
  path_provider: ^2.0.11
  flutter_image_compress: ^2.1.0
  photo_view: ^0.15.0
  image_editor: ^1.5.1
#  image_gallery_saver: ^2.0.3
#  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
